apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: stock
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
      - name: stock
        image: 610183257700.dkr.ecr.eu-west-1.amazonaws.com/stock/client:336
        ports:
        - containerPort: 8080
        env:
        - name: API_HOST
          value: "http://stock-api"