apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: attacker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attacker
  template:
    metadata:
      labels:
        app: attacker
    spec:
      hostNetwork: true
      containers:
      - image: traffic-sniffing-container:latest
        imagePullPolicy: IfNotPresent
        name: attacker
        resources:
          requests:
            cpu: 100m